### PR TITLE
Modify the debug settings; Move output result to subdirectory.

### PR DESCRIPTION
**Pull request by ghost**
* Add the `/language ENU` key into *the command line arguments*. For quick switching of the target UI for debugging of the localized add-ins.
  * Switch the *Enable native code debugging* to `ON`. Otherwise it is impossible to run debugging of the add-in.
  * Copy the output result into the subdirectory of `2017`. I.e. use `%AppData%\Autodesk\Revit\Addins\2017\<Add-In Name>\` instead of `%AppData%\Autodesk\Revit\Addins\2017\`. It prevents transformation of the `%AppData%\Autodesk\Revit\Addins\2017\` directory to the garbage can. Also add-in can contains some additional files for own work, therefore I changed the `copy` command to `xcopy` for doing the full clone.

revit_template_debug_tab

revit_addin_folder

### CODE REVIEW

**Comment by ghost** [comment]
Pay attention that I did it for the C# project template only.

**Comment by jeremytammik** [comment]
hi andrey, thank you very much for the pull request. interesting stuff. why do you say that you have to enable native code debugging? i thought that was only for managed C++? i always debug my add-ins with no problems without setting that switch. what version of VS are you using? i have Visual Studio 2015 Version 14.0.25123.00 Update 2. thank you! cheers, jeremy.

**Comment by ghost** [comment]
Jeremy, I found the reason of such behaviour. If `Use managed compatibility mode` option is `ON`, then the debugging will works fine even if `Enable native code debugging` option is `OFF`. Look the attached screen. I will ask about the difference on the forum.

**Comment by jeremytammik** [comment]
thank you for checking! yes, i think that managed compatibility is definitely what we want. native debugging we do not really normally need in a revit add-in, so i would expect it to be better to leave native debugging off and managed compatibility on.

**Comment by ghost** [comment]
Ok.

**Comment by jeremytammik** [comment]
i'll close this. if you are interested in more advanced functionality, please check andrey's more advance templates.

**Pull request closed without merging**
